# Generated by Django 5.2.4 on 2025-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
