# Generated by Django 5.2.4 on 2025-07-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
